[target.x86_64-unknown-linux-gnu]
image = "x86_64-unknown-linux-gnu:latest"

[target.x86_64-unknown-linux-musl]
image = "x86_64-unknown-linux-musl:latest"

[target.aarch64-unknown-linux-musl]
image = "aarch64-unknown-linux-musl:latest"

[target.arm-unknown-linux-musleabihf]
image = "arm-unknown-linux-musleabihf:latest"
